steps:
  # Step 0: Upgrade gcloud CLI + Tạo subnet dualstack-subnet1
  - name: 'google/cloud-sdk:slim'
    id: 'Setup Gcloud + Subnet'
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update && apt-get install -y curl python3-distutils
        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-475.0.0-linux-x86_64.tar.gz
        tar -xzf google-cloud-sdk-475.0.0-linux-x86_64.tar.gz
        ./google-cloud-sdk/install.sh --quiet
        ./google-cloud-sdk/bin/gcloud components install kubectl --quiet
        ./google-cloud-sdk/bin/gcloud version
          
        # Tạo GKE cluster Dual-Stack
        ./google-cloud-sdk/bin/gcloud container clusters create ${_CLUSTER_NAME} \
          --region=${_REGION} \
          --release-channel=regular \
          --stack-type=ipv4-ipv6 \
          --ipv6-access-type=external \
          --enable-dataplane-v2 \
          --enable-private-nodes \
          --enable-ip-alias \
          --num-nodes=2 \
          --machine-type=e2-medium \
          --disk-size=7 \
          --network=${_VPC_NAME} \
          --create-subnetwork=name=${_SUBNET_NAME},range=192.168.1.0/24 \
          --project=${_PROJECT_ID}

  # Step 1: Get credentials for GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Get GKE Credentials'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} \
          --region ${_REGION} \
          --project ${_PROJECT_ID}

  # Step 2: Deploy App Services
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy App Services'
    args:
      - apply
      - '-f'
      - 'kltn_ecommerce_app/release/kubernetes-manifests_dualstack.yaml'

  # Step 3: Deploy Monitoring Stack (Prometheus + Grafana)
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy Monitoring Stack'
    entrypoint: bash
    args:
      - -c
      - |
        if [ -f kltn_ecommerce_app/release/auto_deploy_monitor.sh ]; then
          chmod +x kltn_ecommerce_app/release/auto_deploy_monitor.sh
          ./kltn_ecommerce_app/release/auto_deploy_monitor.sh
        else
          echo "Monitor script not found, skipping..."
        fi

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _PROJECT_ID: devops-gcp-456308
  _PROJECT_NUMBER: "343668063209"
  _CLUSTER_NAME: ecommerce-cluster1
  _REGION: us-central1
  _VPC_NAME: myvpc
  _SUBNET_NAME: dualstack-subnet1
