steps:
  # Step 1: Tạo GKE cluster Dual-stack
  - name: 'google/cloud-sdk:latest'
    id: 'Create Dual-Stack GKE Cluster'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters create ${_CLUSTER_NAME} \
          --region=${_REGION} \
          --release-channel=regular \
          --stack-type=ipv4-ipv6 \
          --datapath-provider=ADVANCED_DATAPATH \
          --enable-private-nodes \
          --enable-ip-alias \
          --num-nodes=3 \
          --machine-type=e2-medium \
          --network=${_VPC_NAME} \
          --subnetwork=${_SUBNET_NAME} \
          --project=${_PROJECT_ID}

  # Step 2: Lấy credentials để apply
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Get GKE Credentials'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} \
          --region ${_REGION} \
          --project ${_PROJECT_ID}

  # Step 3: Triển khai các service trong manifest dualstack
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy App Services'
    args:
      - apply
      - '-f'
      - 'kltn_ecommerce_app/release/kubernetes-manifests_dualstack.yaml'

  # Step 4: Deploy hệ thống Monitoring (Prometheus + Grafana)
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy Monitoring Stack'
    entrypoint: bash
    args:
      - -c
      - |
        chmod +x kltn_ecommerce_app/release/auto_deploy_monitor.sh
        ./kltn_ecommerce_app/release/auto_deploy_monitor.sh

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _PROJECT_ID: devops-gcp-456308
  _PROJECT_NUMBER: "343668063209"
  _CLUSTER_NAME: ecommerce-cluster1
  _REGION: us-central1
  _VPC_NAME: myvpc
  _SUBNET_NAME: dualstack-subnet
